spring.application.name=employee
server.port=8080

# H2 Database & Web Console Configurations

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:dcbapp
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

# 1. Database Connection URL (Replace with your server, port, and database name)
spring.datasource.url=jdbc:sqlserver://emp-server1.database.windows.net:1433;database=employeeDB1;user=emp-server1@emp-server1;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# 2. Database Authentication Credentials
spring.datasource.username=emp-server1
spring.datasource.password=Postmaster@2026

# 3. Database Driver Class Name (Matches your database vendor)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# JPA & Hibernate Configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

spring.kafka.bootstrap-servers=employee-kafka-ns.servicebus.windows.net:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://employee-kafka-ns.servicebus.windows.net/;SharedAccessKeyName=kafka-policy;SharedAccessKey=7TZ8OmeqrdWV7BlW4VjHRIx7BX38XuR+A+AEhNW711g=;EntityPath=employee-events"


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arvind62pintu@gmail.com
spring.mail.password=deqysdlmgnkotlgu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true