spring.application.name=employee
server.port=8080

# 1. Database Connection URL (Replace with your server, port, and database name)
spring.datasource.url=jdbc:sqlserver://emp-server1.database.windows.net:1433;database=employeeDB1;user=emp-server1@emp-server1;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# 2. Database Authentication Credentials
spring.datasource.username=emp-server1
#spring.datasource.password=Postmaster@2026

# Disable Azure Key Vault initialization during tests
spring.cloud.azure.keyvault.secret.property-sources.enabled=false

# Provide a mock database password so the context loads successfully
#spring.datasource.password=mockPasswordForTesting

# Tell Spring where your vault lives (use the base vault URL, not the secret URL)
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://emp-key-vault1.vault.azure.net/
# Map your database password directly to your Key Vault secret name
spring.datasource.password=${emp-server1}

# 3. Database Driver Class Name (Matches your database vendor)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# JPA & Hibernate Configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

spring.kafka.bootstrap-servers=employee-kafka-ns.servicebus.windows.net:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

#spring.kafka.properties.sasl.jaas.config=${KAFKA_JAAS_CONFIG}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arvind62pintu@gmail.com
spring.mail.password=deqysdlmgnkotlgu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true